// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqNWyFZf695ep8FJA0rPiNy2D09CAmWPA',
    appId: '1:326402988845:android:dd8b7f7af71216f7e951a4',
    messagingSenderId: '326402988845',
    projectId: 'canvas-griffin-233009',
    databaseURL: 'https://canvas-griffin-233009.firebaseio.com',
    storageBucket: 'canvas-griffin-233009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGuPQ_PncWa72yKfcoyJg4AlBQ2QdOiU',
    appId: '1:326402988845:ios:b73b9221d7f38e6ee951a4',
    messagingSenderId: '326402988845',
    projectId: 'canvas-griffin-233009',
    databaseURL: 'https://canvas-griffin-233009.firebaseio.com',
    storageBucket: 'canvas-griffin-233009.appspot.com',
    androidClientId: '326402988845-ljeejnsmv26kg95j4f64sirstci5p31i.apps.googleusercontent.com',
    iosClientId: '326402988845-j47us23jd71q3j22opsiqo721kll0gqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieania',
  );
}
